@url = https://8080-marcoweb-gamessw22024-y00ijzshvwj.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome" : "XBox"
}

###
DELETE {{url}}/plataformas/1

###
PUT {{url}}/plataformas/3
Content-Type: application/json

{
    "nome": "Alterado"
}